name: dotnet-workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: setup
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: restore
      run: dotnet restore .\src\Integrify.sln
    - name: build
      run: dotnet build .\src\Integrify.sln --no-restore
